### ISSUE TITLE
Proposal: Remove radix rule

### ISSUE THREAD

**Issue by yomed** [eBay/eslint-config-ebay#3]
`radix` is currently enforced here:
https://github.com/eBay/eslint-config-ebay/blob/b60daea8ce4c7dba25fae69bfc9af31ed84dda32/rules/bp.js#L119-L120

Pre-ES5, this can be useful for the edge case of octo literals, but `no-octal` is already enforced:
https://github.com/eBay/eslint-config-ebay/blob/b60daea8ce4c7dba25fae69bfc9af31ed84dda32/rules/bp.js#L82-L83

On ES5+ there's questionable value in this rule to begin with, as mentioned here: https://eslint.org/docs/rules/radix
> if the code is targeting only ES5-compliant environments passing the radix 10 may be redundant. In such a case you might want to disallow using such a radix.

So, I propose we remove this rule.

**Comment by mikewoo200** [comment]
@yomed I agree with your reasoning. @senthilp What do you think?

**Comment by senthilp** [comment]
@yomed @mwoo It seems reasonable to remove. But what is developers are using this for legacy rules and targeting older browsers? I think even then all browsers now support ES5, so removing should be safe. 

The original reason we added it was because MDN strongly [recommends](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt#ECMAScript_5_removes_octal_interpretation) it. I am fine if everyone feels it is redundant now.

**Comment by mikewoo200** [comment]
Since I haven't heard from anyone else, I removed the radix rule.

`eslint-config-ebay@^0.1.7`

https://github.com/eBay/eslint-config-ebay/tree/release-0.1.7
